### ISSUE TITLE
关于此项目后期维护

### ISSUE THREAD

**Issue by JeffreyBool** [JeffreyBool/yicms#3]
# 关于此项目后期维护打算

- [ ] 项目重构.

- [ ] 提供一键安装.

- [ ] 想做成开源cms.

如果你对本项目继续开源下去愿意提供力量,请联系我: 1402992668@qq.com

**Comment by bossikill** [comment]
用大佬的框架,一个月996肝了一个游戏日志收集系统出来,今天星期六还在加班,感觉身体被掏空了.

**Comment by JeffreyBool** [comment]
666------------------ 原始邮件 ------------------
发件人: "Jugg"<notifications@github.com>
发送时间: 2020年4月18日(星期六) 下午4:19
收件人: "JeffreyBool/yicms"<yicms@noreply.github.com>;
抄送: "JeffreyBool"<1402992668@qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [JeffreyBool/yicms] 关于此项目后期维护 (#3)




 
用大佬的框架,一个月996肝了一个游戏日志收集系统出来,今天星期六还在加班,感觉身体被掏空了.
 
&mdash;
